<?php
/**
 * RecommendationsAPIApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Groupby\RetailApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Groupby\RetailApiClient\ApiException;
use Groupby\RetailApiClient\Configuration;
use Groupby\RetailApiClient\HeaderSelector;
use Groupby\RetailApiClient\ObjectSerializer;

/**
 * RecommendationsAPIApi Class Doc Comment
 *
 * @category Class
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecommendationsAPIApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'predict' => [
            'application/json',
        ],
        'predictV2' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation predict
     *
     * Provide Recommendations AI functionality.
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predict'] to see the possible values for this operation
     *
     * @throws \Groupby\RetailApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Groupby\RetailApiClient\Model\PredictResults|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse
     * @deprecated
     */
    public function predict($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predict'][0])
    {
        list($response) = $this->predictWithHttpInfo($x_groupby_customer_id, $recommendations_request, $hostIndex, $variables, $contentType);
        return $response;
    }

    /**
     * Operation predictWithHttpInfo
     *
     * Provide Recommendations AI functionality.
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predict'] to see the possible values for this operation
     *
     * @throws \Groupby\RetailApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Groupby\RetailApiClient\Model\PredictResults|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function predictWithHttpInfo($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predict'][0])
    {
        $request = $this->predictRequest($x_groupby_customer_id, $recommendations_request, $hostIndex, $variables, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Groupby\RetailApiClient\Model\PredictResults' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\PredictResults' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\PredictResults', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Groupby\RetailApiClient\Model\PredictResults';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\PredictResults',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation predictAsync
     *
     * Provide Recommendations AI functionality.
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predict'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function predictAsync($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predict'][0])
    {
        return $this->predictAsyncWithHttpInfo($x_groupby_customer_id, $recommendations_request, $hostIndex, $variables, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation predictAsyncWithHttpInfo
     *
     * Provide Recommendations AI functionality.
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predict'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function predictAsyncWithHttpInfo($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predict'][0])
    {
        $returnType = '\Groupby\RetailApiClient\Model\PredictResults';
        $request = $this->predictRequest($x_groupby_customer_id, $recommendations_request, $hostIndex, $variables, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'predict'
     *
    * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
    * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
    *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predict'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function predictRequest($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predict'][0])
    {

        // verify the required parameter 'x_groupby_customer_id' is set
        if ($x_groupby_customer_id === null || (is_array($x_groupby_customer_id) && count($x_groupby_customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_groupby_customer_id when calling predict'
            );
        }

        // verify the required parameter 'recommendations_request' is set
        if ($recommendations_request === null || (is_array($recommendations_request) && count($recommendations_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $recommendations_request when calling predict'
            );
        }


        $resourcePath = '/api/predict';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_groupby_customer_id !== null) {
            $headerParams['X-Groupby-Customer-Id'] = ObjectSerializer::toHeaderValue($x_groupby_customer_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($recommendations_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($recommendations_request));
            } else {
                $httpBody = $recommendations_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        # Preserve the original behavior of server indexing.
        if ($hostIndex === null) {
            $hostIndex = $this->hostIndex;
        }

        $hostSettings = $this->getHostSettingsForpredict();

        if ($hostIndex < 0 || $hostIndex >= count($hostSettings)) {
            throw new \InvalidArgumentException("Invalid index {$hostIndex} when selecting the host. Must be less than ".count($hostSettings));
        }
        $operationHost = Configuration::getHostString($hostSettings, $hostIndex, $variables);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Returns an array of host settings for Operation predict
     *
     * @return array an array of host settings
     */
    protected function getHostSettingsForpredict(): array
    {
        return [
            [
                "url" => "https://recsapi.{environment}.groupbycloud.com",
                "description" => "No description provided",
                "variables" => [
                    "environment" => [
                    "description" => "No description provided",
                    "default_value" => "YOUR_ENV_HERE",
                    ]
                ]
            ]
        ];
    }

    /**
     * Operation predictV2
     *
     * Provide Recommendations AI functionality.
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predictV2'] to see the possible values for this operation
     *
     * @throws \Groupby\RetailApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Groupby\RetailApiClient\Model\PredictResults|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse
     */
    public function predictV2($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predictV2'][0])
    {
        list($response) = $this->predictV2WithHttpInfo($x_groupby_customer_id, $recommendations_request, $hostIndex, $variables, $contentType);
        return $response;
    }

    /**
     * Operation predictV2WithHttpInfo
     *
     * Provide Recommendations AI functionality.
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predictV2'] to see the possible values for this operation
     *
     * @throws \Groupby\RetailApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Groupby\RetailApiClient\Model\PredictResults|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse|\Groupby\RetailApiClient\Model\RecommendationsErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function predictV2WithHttpInfo($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predictV2'][0])
    {
        $request = $this->predictV2Request($x_groupby_customer_id, $recommendations_request, $hostIndex, $variables, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Groupby\RetailApiClient\Model\PredictResults' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\PredictResults' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\PredictResults', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\RecommendationsErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Groupby\RetailApiClient\Model\PredictResults';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\PredictResults',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\RecommendationsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation predictV2Async
     *
     * Provide Recommendations AI functionality.
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predictV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function predictV2Async($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predictV2'][0])
    {
        return $this->predictV2AsyncWithHttpInfo($x_groupby_customer_id, $recommendations_request, $hostIndex, $variables, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation predictV2AsyncWithHttpInfo
     *
     * Provide Recommendations AI functionality.
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predictV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function predictV2AsyncWithHttpInfo($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predictV2'][0])
    {
        $returnType = '\Groupby\RetailApiClient\Model\PredictResults';
        $request = $this->predictV2Request($x_groupby_customer_id, $recommendations_request, $hostIndex, $variables, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'predictV2'
     *
    * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
    * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://recsapi.{environment}.groupbycloud.com
     *  Variables:
    *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\RecommendationsRequest $recommendations_request Request that should be populated to configure a recommendations API call made by the client. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['predictV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function predictV2Request($x_groupby_customer_id, $recommendations_request, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['predictV2'][0])
    {

        // verify the required parameter 'x_groupby_customer_id' is set
        if ($x_groupby_customer_id === null || (is_array($x_groupby_customer_id) && count($x_groupby_customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_groupby_customer_id when calling predictV2'
            );
        }

        // verify the required parameter 'recommendations_request' is set
        if ($recommendations_request === null || (is_array($recommendations_request) && count($recommendations_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $recommendations_request when calling predictV2'
            );
        }


        $resourcePath = '/api/recommendation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_groupby_customer_id !== null) {
            $headerParams['X-Groupby-Customer-Id'] = ObjectSerializer::toHeaderValue($x_groupby_customer_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($recommendations_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($recommendations_request));
            } else {
                $httpBody = $recommendations_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        # Preserve the original behavior of server indexing.
        if ($hostIndex === null) {
            $hostIndex = $this->hostIndex;
        }

        $hostSettings = $this->getHostSettingsForpredictV2();

        if ($hostIndex < 0 || $hostIndex >= count($hostSettings)) {
            throw new \InvalidArgumentException("Invalid index {$hostIndex} when selecting the host. Must be less than ".count($hostSettings));
        }
        $operationHost = Configuration::getHostString($hostSettings, $hostIndex, $variables);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Returns an array of host settings for Operation predictV2
     *
     * @return array an array of host settings
     */
    protected function getHostSettingsForpredictV2(): array
    {
        return [
            [
                "url" => "https://recsapi.{environment}.groupbycloud.com",
                "description" => "No description provided",
                "variables" => [
                    "environment" => [
                    "description" => "No description provided",
                    "default_value" => "YOUR_ENV_HERE",
                    ]
                ]
            ]
        ];
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
