<?php
/**
 * SearchApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Groupby\RetailApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Groupby\RetailApiClient\ApiException;
use Groupby\RetailApiClient\Configuration;
use Groupby\RetailApiClient\HeaderSelector;
use Groupby\RetailApiClient\ObjectSerializer;

/**
 * SearchApi Class Doc Comment
 *
 * @category Class
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'facetSearch' => [
            'application/json',
        ],
        'search' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation facetSearch
     *
     * Provided search functionality
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\FacetSearchRequestDto $facet_search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. Contains original request and information about facet for which extra keys requested. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['facetSearch'] to see the possible values for this operation
     *
     * @throws \Groupby\RetailApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Groupby\RetailApiClient\Model\FacetSearchResponseDto|\Groupby\RetailApiClient\Model\ErrorDto|\Groupby\RetailApiClient\Model\ErrorDto|\Groupby\RetailApiClient\Model\ErrorDto
     */
    public function facetSearch($x_groupby_customer_id, $facet_search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['facetSearch'][0])
    {
        list($response) = $this->facetSearchWithHttpInfo($x_groupby_customer_id, $facet_search_request_dto, $hostIndex, $variables, $contentType);
        return $response;
    }

    /**
     * Operation facetSearchWithHttpInfo
     *
     * Provided search functionality
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\FacetSearchRequestDto $facet_search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. Contains original request and information about facet for which extra keys requested. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['facetSearch'] to see the possible values for this operation
     *
     * @throws \Groupby\RetailApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Groupby\RetailApiClient\Model\FacetSearchResponseDto|\Groupby\RetailApiClient\Model\ErrorDto|\Groupby\RetailApiClient\Model\ErrorDto|\Groupby\RetailApiClient\Model\ErrorDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function facetSearchWithHttpInfo($x_groupby_customer_id, $facet_search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['facetSearch'][0])
    {
        $request = $this->facetSearchRequest($x_groupby_customer_id, $facet_search_request_dto, $hostIndex, $variables, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Groupby\RetailApiClient\Model\FacetSearchResponseDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\FacetSearchResponseDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\FacetSearchResponseDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Groupby\RetailApiClient\Model\ErrorDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\ErrorDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\ErrorDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Groupby\RetailApiClient\Model\ErrorDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\ErrorDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\ErrorDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Groupby\RetailApiClient\Model\ErrorDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\ErrorDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\ErrorDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Groupby\RetailApiClient\Model\FacetSearchResponseDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\FacetSearchResponseDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation facetSearchAsync
     *
     * Provided search functionality
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\FacetSearchRequestDto $facet_search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. Contains original request and information about facet for which extra keys requested. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['facetSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function facetSearchAsync($x_groupby_customer_id, $facet_search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['facetSearch'][0])
    {
        return $this->facetSearchAsyncWithHttpInfo($x_groupby_customer_id, $facet_search_request_dto, $hostIndex, $variables, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation facetSearchAsyncWithHttpInfo
     *
     * Provided search functionality
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\FacetSearchRequestDto $facet_search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. Contains original request and information about facet for which extra keys requested. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['facetSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function facetSearchAsyncWithHttpInfo($x_groupby_customer_id, $facet_search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['facetSearch'][0])
    {
        $returnType = '\Groupby\RetailApiClient\Model\FacetSearchResponseDto';
        $request = $this->facetSearchRequest($x_groupby_customer_id, $facet_search_request_dto, $hostIndex, $variables, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'facetSearch'
     *
    * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
    * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
    *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\FacetSearchRequestDto $facet_search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. Contains original request and information about facet for which extra keys requested. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['facetSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function facetSearchRequest($x_groupby_customer_id, $facet_search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['facetSearch'][0])
    {

        // verify the required parameter 'x_groupby_customer_id' is set
        if ($x_groupby_customer_id === null || (is_array($x_groupby_customer_id) && count($x_groupby_customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_groupby_customer_id when calling facetSearch'
            );
        }

        // verify the required parameter 'facet_search_request_dto' is set
        if ($facet_search_request_dto === null || (is_array($facet_search_request_dto) && count($facet_search_request_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $facet_search_request_dto when calling facetSearch'
            );
        }


        $resourcePath = '/api/search/facet';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_groupby_customer_id !== null) {
            $headerParams['X-Groupby-Customer-Id'] = ObjectSerializer::toHeaderValue($x_groupby_customer_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($facet_search_request_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($facet_search_request_dto));
            } else {
                $httpBody = $facet_search_request_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        # Preserve the original behavior of server indexing.
        if ($hostIndex === null) {
            $hostIndex = $this->hostIndex;
        }

        $hostSettings = $this->getHostSettingsForfacetSearch();

        if ($hostIndex < 0 || $hostIndex >= count($hostSettings)) {
            throw new \InvalidArgumentException("Invalid index {$hostIndex} when selecting the host. Must be less than ".count($hostSettings));
        }
        $operationHost = Configuration::getHostString($hostSettings, $hostIndex, $variables);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Returns an array of host settings for Operation facetSearch
     *
     * @return array an array of host settings
     */
    protected function getHostSettingsForfacetSearch(): array
    {
        return [
            [
                "url" => "https://search.{environment}.groupbycloud.com",
                "description" => "No description provided",
                "variables" => [
                    "environment" => [
                    "description" => "No description provided",
                    "default_value" => "YOUR_ENV_HERE",
                    ]
                ]
            ]
        ];
    }

    /**
     * Operation search
     *
     * Provided search functionality
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\SearchRequestDto $search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \Groupby\RetailApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Groupby\RetailApiClient\Model\SearchResponseDto|\Groupby\RetailApiClient\Model\ErrorDto|\Groupby\RetailApiClient\Model\ErrorDto|\Groupby\RetailApiClient\Model\ErrorDto
     */
    public function search($x_groupby_customer_id, $search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['search'][0])
    {
        list($response) = $this->searchWithHttpInfo($x_groupby_customer_id, $search_request_dto, $hostIndex, $variables, $contentType);
        return $response;
    }

    /**
     * Operation searchWithHttpInfo
     *
     * Provided search functionality
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\SearchRequestDto $search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \Groupby\RetailApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Groupby\RetailApiClient\Model\SearchResponseDto|\Groupby\RetailApiClient\Model\ErrorDto|\Groupby\RetailApiClient\Model\ErrorDto|\Groupby\RetailApiClient\Model\ErrorDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchWithHttpInfo($x_groupby_customer_id, $search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['search'][0])
    {
        $request = $this->searchRequest($x_groupby_customer_id, $search_request_dto, $hostIndex, $variables, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Groupby\RetailApiClient\Model\SearchResponseDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\SearchResponseDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\SearchResponseDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Groupby\RetailApiClient\Model\ErrorDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\ErrorDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\ErrorDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Groupby\RetailApiClient\Model\ErrorDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\ErrorDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\ErrorDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Groupby\RetailApiClient\Model\ErrorDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Groupby\RetailApiClient\Model\ErrorDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Groupby\RetailApiClient\Model\ErrorDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Groupby\RetailApiClient\Model\SearchResponseDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\SearchResponseDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Groupby\RetailApiClient\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchAsync
     *
     * Provided search functionality
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\SearchRequestDto $search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchAsync($x_groupby_customer_id, $search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['search'][0])
    {
        return $this->searchAsyncWithHttpInfo($x_groupby_customer_id, $search_request_dto, $hostIndex, $variables, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchAsyncWithHttpInfo
     *
     * Provided search functionality
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
     *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\SearchRequestDto $search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchAsyncWithHttpInfo($x_groupby_customer_id, $search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['search'][0])
    {
        $returnType = '\Groupby\RetailApiClient\Model\SearchResponseDto';
        $request = $this->searchRequest($x_groupby_customer_id, $search_request_dto, $hostIndex, $variables, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'search'
     *
    * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
    * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://search.{environment}.groupbycloud.com
     *  Variables:
    *    - environment:  No description provided
     *
     * @param  string $x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name. (required)
     * @param  \Groupby\RetailApiClient\Model\SearchRequestDto $search_request_dto Request that should be populated to configure a search API call, made by the client on behalf of a shopper. (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchRequest($x_groupby_customer_id, $search_request_dto, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['search'][0])
    {

        // verify the required parameter 'x_groupby_customer_id' is set
        if ($x_groupby_customer_id === null || (is_array($x_groupby_customer_id) && count($x_groupby_customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_groupby_customer_id when calling search'
            );
        }

        // verify the required parameter 'search_request_dto' is set
        if ($search_request_dto === null || (is_array($search_request_dto) && count($search_request_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $search_request_dto when calling search'
            );
        }


        $resourcePath = '/api/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_groupby_customer_id !== null) {
            $headerParams['X-Groupby-Customer-Id'] = ObjectSerializer::toHeaderValue($x_groupby_customer_id);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($search_request_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($search_request_dto));
            } else {
                $httpBody = $search_request_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        # Preserve the original behavior of server indexing.
        if ($hostIndex === null) {
            $hostIndex = $this->hostIndex;
        }

        $hostSettings = $this->getHostSettingsForsearch();

        if ($hostIndex < 0 || $hostIndex >= count($hostSettings)) {
            throw new \InvalidArgumentException("Invalid index {$hostIndex} when selecting the host. Must be less than ".count($hostSettings));
        }
        $operationHost = Configuration::getHostString($hostSettings, $hostIndex, $variables);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Returns an array of host settings for Operation search
     *
     * @return array an array of host settings
     */
    protected function getHostSettingsForsearch(): array
    {
        return [
            [
                "url" => "https://search.{environment}.groupbycloud.com",
                "description" => "No description provided",
                "variables" => [
                    "environment" => [
                    "description" => "No description provided",
                    "default_value" => "YOUR_ENV_HERE",
                    ]
                ]
            ]
        ];
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
