<?php
/**
 * Stats
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Groupby\RetailApiClient\Model;

use \ArrayAccess;
use \Groupby\RetailApiClient\ObjectSerializer;

/**
 * Stats Class Doc Comment
 *
 * @category Class
 * @description Object with base response information. Contains count of returned suggestions and time spent to handle the request.
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Stats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Stats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'search_count' => 'int',
        'autocomplete_response' => 'int',
        'extended_attributes_count' => 'int',
        'extended_attributes_response' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'search_count' => 'int32',
        'autocomplete_response' => 'int64',
        'extended_attributes_count' => 'int32',
        'extended_attributes_response' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'search_count' => false,
		'autocomplete_response' => false,
		'extended_attributes_count' => false,
		'extended_attributes_response' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'search_count' => 'searchCount',
        'autocomplete_response' => 'autocompleteResponse',
        'extended_attributes_count' => 'extendedAttributesCount',
        'extended_attributes_response' => 'extendedAttributesResponse'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'search_count' => 'setSearchCount',
        'autocomplete_response' => 'setAutocompleteResponse',
        'extended_attributes_count' => 'setExtendedAttributesCount',
        'extended_attributes_response' => 'setExtendedAttributesResponse'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'search_count' => 'getSearchCount',
        'autocomplete_response' => 'getAutocompleteResponse',
        'extended_attributes_count' => 'getExtendedAttributesCount',
        'extended_attributes_response' => 'getExtendedAttributesResponse'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('search_count', $data ?? [], null);
        $this->setIfExists('autocomplete_response', $data ?? [], null);
        $this->setIfExists('extended_attributes_count', $data ?? [], null);
        $this->setIfExists('extended_attributes_response', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets search_count
     *
     * @return int|null
     */
    public function getSearchCount()
    {
        return $this->container['search_count'];
    }

    /**
     * Sets search_count
     *
     * @param int|null $search_count Count of suggested sentences in response.
     *
     * @return self
     */
    public function setSearchCount($search_count)
    {
        if (is_null($search_count)) {
            throw new \InvalidArgumentException('non-nullable search_count cannot be null');
        }
        $this->container['search_count'] = $search_count;

        return $this;
    }

    /**
     * Gets autocomplete_response
     *
     * @return int|null
     */
    public function getAutocompleteResponse()
    {
        return $this->container['autocomplete_response'];
    }

    /**
     * Sets autocomplete_response
     *
     * @param int|null $autocomplete_response Time in milliseconds taken by autocomplete service to handle request and send response.
     *
     * @return self
     */
    public function setAutocompleteResponse($autocomplete_response)
    {
        if (is_null($autocomplete_response)) {
            throw new \InvalidArgumentException('non-nullable autocomplete_response cannot be null');
        }
        $this->container['autocomplete_response'] = $autocomplete_response;

        return $this;
    }

    /**
     * Gets extended_attributes_count
     *
     * @return int|null
     */
    public function getExtendedAttributesCount()
    {
        return $this->container['extended_attributes_count'];
    }

    /**
     * Sets extended_attributes_count
     *
     * @param int|null $extended_attributes_count Count of extended attributes in autocomplete response.
     *
     * @return self
     */
    public function setExtendedAttributesCount($extended_attributes_count)
    {
        if (is_null($extended_attributes_count)) {
            throw new \InvalidArgumentException('non-nullable extended_attributes_count cannot be null');
        }
        $this->container['extended_attributes_count'] = $extended_attributes_count;

        return $this;
    }

    /**
     * Gets extended_attributes_response
     *
     * @return int|null
     */
    public function getExtendedAttributesResponse()
    {
        return $this->container['extended_attributes_response'];
    }

    /**
     * Sets extended_attributes_response
     *
     * @param int|null $extended_attributes_response Time in milliseconds taken by application to enrich response with extended attributes.
     *
     * @return self
     */
    public function setExtendedAttributesResponse($extended_attributes_response)
    {
        if (is_null($extended_attributes_response)) {
            throw new \InvalidArgumentException('non-nullable extended_attributes_response cannot be null');
        }
        $this->container['extended_attributes_response'] = $extended_attributes_response;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


