<?php
/**
 * ZoneDtoType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Groupby\RetailApiClient\Model;
use \Groupby\RetailApiClient\ObjectSerializer;

/**
 * ZoneDtoType Class Doc Comment
 *
 * @category Class
 * @description Define type of content which is can be stored in zone.
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZoneDtoType
{
    /**
     * Possible values of this enum
     */
    public const CONTENT = 'Content';

    public const RICH_CONTENT = 'Rich_Content';

    public const PRODUCTS = 'Products';

    public const GENERATED_CONTENT = 'Generated_Content';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONTENT,
            self::RICH_CONTENT,
            self::PRODUCTS,
            self::GENERATED_CONTENT
        ];
    }
}


