<?php
/**
 * BiasDtoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Groupby\RetailApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Groupby\RetailApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BiasDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Biases the search results to either increase or decrease product relevancy for products that match the given field and content.
 * @package     Groupby\RetailApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BiasDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BiasDto"
     */
    public function testBiasDto()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "field"
     */
    public function testPropertyField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "strength"
     */
    public function testPropertyStrength()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
